Merge Testing/#0001 android into main
AnnaSolvd/mobile-automation-native pull request #1
Opened 2024-07-31 13:09 UTC by AnnaSolvd

2024-08-05 14:44 UTC, MariuszSolvd requested changes
Ok, I checked iOS overall it looks good. I made some small comments. Some of locators can be changed to iosPredicate, I prefer these ones since it's easier to read. You can change it easily. I mark some of these fields, but some I didn't, since I didn't want to spam you too much with comments. And some minor improvements that I suggested.

2024-08-05 14:44 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/CheckOutInformationIOS.java
> +    @ExtendedFindBy(iosClassChain = "**/XCUIElementTypeTextField[`name == 'test-First Name'`]")
Can be replaced with just Predicate

2024-08-05 14:44 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/CheckOutInformationIOS.java
> +    @ExtendedFindBy(iosClassChain = "**/XCUIElementTypeTextField[`name == 'test-Last Name'`]")
Can be replaced with just Predicate

2024-08-05 14:44 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/CheckOutInformationIOS.java
> +    @ExtendedFindBy(iosClassChain = "**/XCUIElementTypeTextField[`name == 'test-Zip/Postal Code'`]")
Can be replaced with just Predicate

2024-08-05 14:44 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/CheckOutInformationIOS.java
> +    @ExtendedFindBy(iosClassChain = "**/XCUIElementTypeOther[`name == 'test-CONTINUE'`]")
Can be replaced with just Predicate

2024-08-05 14:44 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +    private SwagLabsProduct selectProduct() {
Shouldn't be selectRandomProduct/getRandomProduct?

2024-08-05 14:44 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +        String productPrice = productList.get(0).getPrice();
I think you can replace get(0) with getFirst()

2024-08-05 14:44 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +    public SwagLabsProduct getRandomProduct() {
Why do you have two methods do same thing selectProduct and getRandomProduct?

2024-08-05 14:44 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/LoginPageIOS.java
> +    @ExtendedFindBy(iosClassChain = "**/XCUIElementTypeTextField[`name == 'test-Username'`]")
isoPredicate can be used

2024-08-05 14:44 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +    public ProductPageIOSBase clickRandomProduct() {
Could delegate this method to SwagLabsProduct and from there initPage of ProductPage. So you can get random product and then from instance of the product you can just click on it and get ProductPage

2024-08-06 08:43 UTC, AnnaSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +        String productPrice = productList.get(0).getPrice();
I wanted to use getFirst() but got an error. It turned out that getFirs() is from JDK 21, and in the project I had JDK 14

2024-08-06 09:38 UTC, whetman approved these changes
Looks good to me

2024-08-06 11:01 UTC, AnnaSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +    public ProductPageIOSBase clickRandomProduct() {
Done

2024-08-06 11:01 UTC, AnnaSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +    public SwagLabsProduct getRandomProduct() {
Done

2024-08-06 11:01 UTC, AnnaSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +        String productPrice = productList.get(0).getPrice();
Done

2024-08-06 11:02 UTC, AnnaSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +    private SwagLabsProduct selectProduct() {
Done

2024-08-06 11:04 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +        String productPrice = productList.get(0).getPrice();
Yeah, I saw that you set from java 11 to java 14 in your POM, and I thought you just like to use Java 14 that's why you use 14 xD

2024-08-06 11:25 UTC, AnnaSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/LoginPageIOS.java
> +    @ExtendedFindBy(iosClassChain = "**/XCUIElementTypeTextField[`name == 'test-Username'`]")
I changed iosClassChain to iosPredicate everywhere I could

2024-08-07 08:36 UTC, MariuszSolvd approved these changes
Looks good, well done!

2024-08-07 08:36 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/pages/ios/HomePageIOS.java
> +    public SwagLabsProduct getRandomProduct() {
I see you deleted selectProduct() and now use just getRandomProduct(), good job.

2024-08-07 08:36 UTC, MariuszSolvd commented on src/main/java/com/solvd/swaglabs/gui/components/SwagLabsProduct.java
> +    public ProductPageIOSBase clickProduct() {
Ok, I can see you add click in SwagLabsProduct, I like it!

2024-08-07 08:38 UTC, merged